language: node_js
sudo: required
node_js:
  - 5
  - 6
install:
  - npm install
  - npm install -g bower
  - bower install
script:
  - npm test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_AUTH_TOKEN | pulp login &&
  echo y | pulp publish --no-push
