{ name = "uri"
, dependencies =
  [ "aff"
  , "arrays"
  , "assert"
  , "bifunctors"
  , "console"
  , "control"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "gen"
  , "integers"
  , "js-uri"
  , "maybe"
  , "newtype"
  , "parsing"
  , "partial"
  , "prelude"
  , "profunctor-lenses"
  , "quickcheck"
  , "strings"
  , "tailrec"
  , "these"
  , "transformers"
  , "tuples"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
}
